"""Reviewed, immutable migration data for the 2026-09-03 NY report."""
from __future__ import annotations

MIGRATION_PAYLOAD = {'schema_version': 'ny_market_historical_migration_v1',
 'migration_id': 'ny_market_20260903_after_hours_v3',
 'migration_source': 'reviewed_external_research_snapshot_2026-09-03',
 'verified_at': '2026-09-03T12:04:39+09:00',
 'stable_key': 'ny_market_daily:2026-09-03',
 'market_session_date': '2026-09-02',
 'source_display_contract': 'ny_market_display_v2',
 'target_display_contract': 'ny_market_display_v3',
 'target_research_contract': 'ny_market_after_hours_v2',
 'after_hours_research': [{'ticker': 'AVGO',
                           'company_name': 'Broadcom',
                           'company_description': 'カスタムAIアクセラレーターとデータセンター向けネットワーク半導体、VMwareを含むインフラソフトを展開する企業です。AI半導体の成長と非AI半導体の回復、利益率を同時に見る必要があります。',
                           'source_url': 'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial',
                           'source_type': 'company_ir',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 2,
                           'search_queries': ['"AVGO" 2026-09-02 results',
                                              '"Broadcom" investor relations 2026-09-02'],
                           'searched_sources': ['https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'],
                           'event_type': 'earnings',
                           'same_day_developments': [],
                           'why_moved': 'Q3はbeatでも、Q4売上見通し$34.8Bが市場予想$35.05Bを下回り、非AI半導体の弱さがAIの急成長を上回る失望材料になりました。',
                           'investment_readthrough': 'カスタムASICとネットワーク需要はAI設備投資の裾野拡大を示す一方、汎用半導体には回復の遅れを示すread-throughです。',
                           'watch_items': ['AI半導体の受注から売上への転換', '非AI半導体の回復', '非GAAP営業利益率66%の維持'],
                           'qualitative_evidence': {'why_moved': ['$34.8B', '$35.05B'],
                                                    'investment_readthrough': ['カスタムASIC',
                                                                               'ネットワーク']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial',
                                             'source_kind': 'company_ir'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'}],
                           'reported_results': [{'summary': 'Q3売上は$29.59Bで前年比86%増、調整後EPSは$3.32でした。',
                                                 'evidence_tokens': ['$29.59B', '86%', '$3.32'],
                                                 'source_url': 'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial'}],
                           'consensus_comparison': [{'summary': '調整後EPSは$3.32と市場予想$3.21を上回りました。',
                                                     'actual': '$3.32',
                                                     'estimate': '$3.21',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                    {'summary': 'Q4売上見通し$34.8Bは市場予想$35.05Bを下回りました。',
                                                     'actual': '$34.8B',
                                                     'estimate': '$35.05B',
                                                     'outcome': 'miss',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}],
                           'guidance': [{'summary': 'Q4売上を$34.8B、AI半導体売上を$21.7Bで前年比236%増と見込みました。',
                                         'evidence_tokens': ['$34.8B', '$21.7B', '236%'],
                                         'source_url': 'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial'}],
                           'guidance_comparison': [],
                           'key_kpis': [{'summary': 'Q3のAI半導体売上は$16.7Bで前年比221%増、前四半期比54%増でした。',
                                         'evidence_tokens': ['$16.7B', '221%', '54%'],
                                         'source_url': 'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial'}],
                           'background_context': [],
                           'after_hours_change_pct': -3.5,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'Broadcom',
                           'after_hours_reaction': {'change_pct': -3.5,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'},
                          {'ticker': 'SNOW',
                           'company_name': 'Snowflake',
                           'company_description': '企業データをクラウド上に蓄積・分析し、AIアプリやエージェントが使うデータ基盤を提供する会社です。利用量課金のため、製品売上とデータ消費、AI機能の実利用が重要です。',
                           'source_url': 'https://www.sec.gov/Archives/edgar/data/1640147/000164014726000033/fy2027q2earnings.htm',
                           'source_type': 'sec',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 3,
                           'search_queries': ['"SNOW" 2026-09-02 results',
                                              '"Snowflake" investor relations 2026-09-02'],
                           'searched_sources': ['https://www.sec.gov/Archives/edgar/data/1640147/000164014726000033/fy2027q2earnings.htm',
                                                'https://s26.q4cdn.com/463892824/files/doc_financials/2027/q1/CORRECTED-TRANSCRIPT_-Snowflake-Inc-SNOW-US-Q1-2027-Earnings-Call-27-May-2026-5_00-PM-ET.pdf',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'],
                           'event_type': 'earnings',
                           'same_day_developments': [],
                           'why_moved': '製品売上の伸びが3四半期連続で加速し、EPSのbeatとFY27製品売上$6.07Bへの上方修正が、AI需要を実課金へ変える力を裏付けました。',
                           'investment_readthrough': 'CoCoとCoWorkの利用口座拡大は、AI機能が将来の製品消費増加につながる可能性と、実験段階から本番利用へ移る需要を示しています。',
                           'watch_items': ['NRR 126%の再加速', 'RPO $9.00Bの売上転換', 'AI利用増とFCFマージンの両立'],
                           'qualitative_evidence': {'why_moved': ['3四半期連続', '$6.07B'],
                                                    'investment_readthrough': ['CoCo', '製品消費']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://www.sec.gov/Archives/edgar/data/1640147/000164014726000033/fy2027q2earnings.htm',
                                             'source_kind': 'sec'},
                                            {'label': 'AWS契約・前四半期説明会',
                                             'url': 'https://s26.q4cdn.com/463892824/files/doc_financials/2027/q1/CORRECTED-TRANSCRIPT_-Snowflake-Inc-SNOW-US-Q1-2027-Earnings-Call-27-May-2026-5_00-PM-ET.pdf',
                                             'source_kind': 'earnings_call'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'}],
                           'reported_results': [{'summary': 'Q2総売上は$1.55B、製品売上は$1.49Bで前年比37%増、NRRは126%、RPOは$9.00Bで30%増でした。',
                                                 'evidence_tokens': ['$1.55B',
                                                                     '$1.49B',
                                                                     '37%',
                                                                     '126%',
                                                                     '$9.00B',
                                                                     '30%'],
                                                 'source_url': 'https://www.sec.gov/Archives/edgar/data/1640147/000164014726000033/fy2027q2earnings.htm'}],
                           'consensus_comparison': [{'summary': '調整後EPSは$0.62と市場予想$0.45を上回りました。',
                                                     'actual': '$0.62',
                                                     'estimate': '$0.45',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}],
                           'guidance': [],
                           'guidance_comparison': [{'summary': 'FY27製品売上見通しを$5.84Bから$6.07Bへ引き上げました。',
                                                    'previous': '$5.84B',
                                                    'current': '$6.07B',
                                                    'direction': 'raised',
                                                    'source_url': 'https://www.sec.gov/Archives/edgar/data/1640147/000164014726000033/fy2027q2earnings.htm'}],
                           'key_kpis': [{'summary': 'CoCoは9,100口座、CoWorkは5,800口座へ拡大し、会社は両製品が新規workloadとplatform '
                                                    'consumptionを促していると説明しました。',
                                         'evidence_tokens': ['9,100',
                                                             '5,800',
                                                             'platform consumption'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/1640147/000164014726000033/fy2027q2earnings.htm'}],
                           'background_context': [{'summary': '前四半期の5月27日にAWSと5年間$6Bの利用・共同販売契約を発表しており、中期的な利用拡大を支える背景材料です。',
                                                   'evidence_tokens': ['5月27日',
                                                                       'AWS',
                                                                       '5年間',
                                                                       '$6B'],
                                                   'source_url': 'https://s26.q4cdn.com/463892824/files/doc_financials/2027/q1/CORRECTED-TRANSCRIPT_-Snowflake-Inc-SNOW-US-Q1-2027-Earnings-Call-27-May-2026-5_00-PM-ET.pdf',
                                                   'announced_at': '2026-05-27',
                                                   'temporal_status': 'prior_period'}],
                           'after_hours_change_pct': 21.0,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'Snowflake',
                           'after_hours_reaction': {'change_pct': 21.0,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'},
                          {'ticker': 'HPE',
                           'company_name': 'Hewlett Packard Enterprise',
                           'company_description': '企業向けサーバー、クラウド基盤と、Juniper統合後のネットワーク製品を提供します。AI需要、ネットワーク成長、利益率と部品供給が焦点です。',
                           'source_url': 'https://www.sec.gov/Archives/edgar/data/1645590/000164559026000078/ex-991x922026x8k.htm',
                           'source_type': 'sec',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 3,
                           'search_queries': ['"HPE" 2026-09-02 results',
                                              '"Hewlett Packard Enterprise" investor relations '
                                              '2026-09-02'],
                           'searched_sources': ['https://www.sec.gov/Archives/edgar/data/1645590/000164559026000078/ex-991x922026x8k.htm',
                                                'https://investors.hpe.com/~/media/Files/H/HP-Enterprise-IR/documents/q1-2026/hpe-q1-26-earnings-transcript.pdf',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'],
                           'event_type': 'earnings',
                           'same_day_developments': [],
                           'why_moved': '全面的なbeatとraiseでも、Dell決算を受けた事前上昇で期待値が高く、Juniper寄与を含む75%のNetworking成長と部品制約を市場が割り引きました。',
                           'investment_readthrough': 'AIサーバーとデータセンターネットワーク需要は強い一方、メモリを含む部品不足が受注を売上へ変える速度とハードウェア利益率を制約します。',
                           'watch_items': ['Juniper統合後のNetworking有機成長',
                                           'メモリ供給と価格転嫁',
                                           'Cloud & AI利益率17.0%の持続性'],
                           'qualitative_evidence': {'why_moved': ['Juniper', '75%'],
                                                    'investment_readthrough': ['メモリ', '利益率']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://www.sec.gov/Archives/edgar/data/1645590/000164559026000078/ex-991x922026x8k.htm',
                                             'source_kind': 'sec'},
                                            {'label': 'FY26 Q1説明会・メモリ制約',
                                             'url': 'https://investors.hpe.com/~/media/Files/H/HP-Enterprise-IR/documents/q1-2026/hpe-q1-26-earnings-transcript.pdf',
                                             'source_kind': 'earnings_call'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'}],
                           'reported_results': [{'summary': 'Q3売上は$12.2Bで前年比34%増、調整後EPSは$1.11、非GAAP営業利益率は16.2%でした。',
                                                 'evidence_tokens': ['$12.2B',
                                                                     '34%',
                                                                     '$1.11',
                                                                     '16.2%'],
                                                 'source_url': 'https://www.sec.gov/Archives/edgar/data/1645590/000164559026000078/ex-991x922026x8k.htm'}],
                           'consensus_comparison': [{'summary': '調整後EPSは$1.11と市場予想$0.92を上回りました。',
                                                     'actual': '$1.11',
                                                     'estimate': '$0.92',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}],
                           'guidance': [{'summary': 'FY26調整後EPSを$3.75–$3.85、FCFを少なくとも$3.75Bへ引き上げました。',
                                         'evidence_tokens': ['$3.75–$3.85', '$3.75B'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/1645590/000164559026000078/ex-991x922026x8k.htm'}],
                           'guidance_comparison': [],
                           'key_kpis': [{'summary': 'Networking売上はJuniper統合を含め75%増、Cloud & '
                                                    'AI売上は25%増で、各営業利益率は22.0%と17.0%でした。',
                                         'evidence_tokens': ['75%', '25%', '22.0%', '17.0%'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/1645590/000164559026000078/ex-991x922026x8k.htm'}],
                           'background_context': [{'summary': '3月9日のFY26 '
                                                              'Q1説明会で、メモリコスト上昇が2026年中続く前提を示しており、今回以前からの背景条件です。',
                                                   'evidence_tokens': ['3月9日', 'メモリコスト', '2026年'],
                                                   'source_url': 'https://investors.hpe.com/~/media/Files/H/HP-Enterprise-IR/documents/q1-2026/hpe-q1-26-earnings-transcript.pdf',
                                                   'announced_at': '2026-03-09',
                                                   'temporal_status': 'prior_period'}],
                           'after_hours_change_pct': -1.0,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'Hewlett Packard Enterprise',
                           'after_hours_reaction': {'change_pct': -1.0,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'},
                          {'ticker': 'NTAP',
                           'company_name': 'NetApp',
                           'company_description': '企業向けストレージとハイブリッドクラウドのデータ管理基盤を提供します。AI向けall-flash需要だけでなく、売上をキャッシュへ変える力と在庫効率が重要です。',
                           'source_url': 'https://investors.netapp.com/news/news-details/2026/NetApp-Reports-First-Quarter-of-Fiscal-Year-2027-Results/default.aspx',
                           'source_type': 'company_ir',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 4,
                           'search_queries': ['"NTAP" 2026-09-02 results',
                                              '"NetApp" investor relations 2026-09-02'],
                           'searched_sources': ['https://investors.netapp.com/news/news-details/2026/NetApp-Reports-First-Quarter-of-Fiscal-Year-2027-Results/default.aspx',
                                                'https://investors.netapp.com/news/news-details/2026/NetApp-Acquires-DataPelago-Making-Data-AI-Ready-at-the-Infrastructure-Layer/default.aspx',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                'https://www.investing.com/news/earnings/netapp-slides-8-despite-beat-on-weaker-cash-flow-concerns-93CH-4886695'],
                           'event_type': 'earnings',
                           'same_day_developments': [],
                           'why_moved': '売上・EPSのbeatと通期上方修正よりも、FCFの35%減と在庫の急増がキャッシュ転換の悪化として重く見られ、sell-the-newsになりました。',
                           'investment_readthrough': 'all-flashとAIデータ基盤需要はストレージ業界に追い風ですが、ハードウェア増産が運転資本を圧迫する局面では利益成長だけで評価できません。',
                           'watch_items': ['在庫$375Mの正常化', 'FCF $401Mの回復', 'DataPelago統合によるAI案件獲得'],
                           'qualitative_evidence': {'why_moved': ['FCF', '在庫'],
                                                    'investment_readthrough': ['all-flash',
                                                                               '運転資本']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://investors.netapp.com/news/news-details/2026/NetApp-Reports-First-Quarter-of-Fiscal-Year-2027-Results/default.aspx',
                                             'source_kind': 'company_ir'},
                                            {'label': 'DataPelago買収発表',
                                             'url': 'https://investors.netapp.com/news/news-details/2026/NetApp-Acquires-DataPelago-Making-Data-AI-Ready-at-the-Infrastructure-Layer/default.aspx',
                                             'source_kind': 'company_ir'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'},
                                                      {'label': '時間外下落・cash flow分析',
                                                       'url': 'https://www.investing.com/news/earnings/netapp-slides-8-despite-beat-on-weaker-cash-flow-concerns-93CH-4886695',
                                                       'source_kind': 'financial_media'}],
                           'reported_results': [{'summary': 'Q1売上は$2.03Bで30%増、調整後EPSは$2.58、billingsは$2.06Bで36%増でした。',
                                                 'evidence_tokens': ['$2.03B',
                                                                     '30%',
                                                                     '$2.58',
                                                                     '$2.06B',
                                                                     '36%'],
                                                 'source_url': 'https://investors.netapp.com/news/news-details/2026/NetApp-Reports-First-Quarter-of-Fiscal-Year-2027-Results/default.aspx'}],
                           'consensus_comparison': [{'summary': '調整後EPSは$2.58と市場予想$2.11を上回りました。',
                                                     'actual': '$2.58',
                                                     'estimate': '$2.11',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}],
                           'guidance': [],
                           'guidance_comparison': [{'summary': 'FY27調整後EPS見通しを$8.70–$9.00から$9.73–$10.03へ引き上げました。',
                                                    'previous': '$8.70–$9.00',
                                                    'current': '$9.73–$10.03',
                                                    'direction': 'raised',
                                                    'source_url': 'https://investors.netapp.com/news/news-details/2026/NetApp-Reports-First-Quarter-of-Fiscal-Year-2027-Results/default.aspx'}],
                           'key_kpis': [{'summary': 'all-flash売上は$1.3Bで47%増でしたが、FCFは$401Mで35%減、在庫は$198Mから$375Mへ増えました。',
                                         'evidence_tokens': ['$1.3B',
                                                             '47%',
                                                             '$401M',
                                                             '35%',
                                                             '$198M',
                                                             '$375M'],
                                         'source_url': 'https://investors.netapp.com/news/news-details/2026/NetApp-Reports-First-Quarter-of-Fiscal-Year-2027-Results/default.aspx'}],
                           'background_context': [{'summary': '7月16日にAIデータ処理基盤DataPelagoの買収を発表済みで、今回以前からの背景材料としてAI案件への統合が焦点です。',
                                                   'evidence_tokens': ['7月16日', 'DataPelago', '買収'],
                                                   'source_url': 'https://investors.netapp.com/news/news-details/2026/NetApp-Acquires-DataPelago-Making-Data-AI-Ready-at-the-Infrastructure-Layer/default.aspx',
                                                   'announced_at': '2026-07-16',
                                                   'temporal_status': 'prior_period'}],
                           'after_hours_change_pct': -7.0,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'NetApp',
                           'after_hours_reaction': {'change_pct': -7.0,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'},
                          {'ticker': 'NTSK',
                           'company_name': 'Netskope',
                           'company_description': '企業のクラウド、Web、AI利用を保護するSASEとデータセキュリティ基盤を提供します。売上より先行するARRと、成長を維持しながら赤字を縮められるかが重要です。',
                           'source_url': 'https://investors.netskope.com/news-releases/news-release-details/netskope-announces-strong-second-quarter-fiscal-2027-financial',
                           'source_type': 'company_ir',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 2,
                           'search_queries': ['"NTSK" 2026-09-02 results',
                                              '"Netskope" investor relations 2026-09-02'],
                           'searched_sources': ['https://investors.netskope.com/news-releases/news-release-details/netskope-announces-strong-second-quarter-fiscal-2027-financial',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'],
                           'event_type': 'earnings',
                           'same_day_developments': [],
                           'why_moved': 'ARR '
                                        '27%成長を保ちながら市場予想より赤字が小さく、通期売上と損失見通しも改善したため、成長と収益性の両立が再評価されました。',
                           'investment_readthrough': 'AI '
                                                     'Securityの初期需要は、生成AI利用の拡大がSASE、データ保護、ネットワーク最適化への追加支出を生むread-throughです。',
                           'watch_items': ['net new ARRの再加速', 'AI Securityの有料化', 'FCFマージン2%の達成'],
                           'qualitative_evidence': {'why_moved': ['ARR 27%', '赤字'],
                                                    'investment_readthrough': ['AI Security',
                                                                               'SASE']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://investors.netskope.com/news-releases/news-release-details/netskope-announces-strong-second-quarter-fiscal-2027-financial',
                                             'source_kind': 'company_ir'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'}],
                           'reported_results': [{'summary': 'Q2売上は$220.5Mで29%増、ARRは$899Mで27%増、調整後1株損失は-$0.03でした。',
                                                 'evidence_tokens': ['$220.5M',
                                                                     '29%',
                                                                     '$899M',
                                                                     '27%',
                                                                     '-$0.03'],
                                                 'source_url': 'https://investors.netskope.com/news-releases/news-release-details/netskope-announces-strong-second-quarter-fiscal-2027-financial'}],
                           'consensus_comparison': [{'summary': '調整後1株損失は-$0.03と市場予想-$0.07より小幅でした。',
                                                     'actual': '-$0.03',
                                                     'estimate': '-$0.07',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}],
                           'guidance': [{'summary': 'FY27売上を$888M–$892M、調整後1株損失を-$0.15と見込み、従来より改善しました。',
                                         'evidence_tokens': ['$888M–$892M', '-$0.15'],
                                         'source_url': 'https://investors.netskope.com/news-releases/news-release-details/netskope-announces-strong-second-quarter-fiscal-2027-financial'}],
                           'guidance_comparison': [],
                           'key_kpis': [{'summary': '非GAAP営業損失率は前年の-20%から-9%へ改善し、AI '
                                                    'Security製品の初期需要も確認しました。',
                                         'evidence_tokens': ['-20%', '-9%', 'AI Security'],
                                         'source_url': 'https://investors.netskope.com/news-releases/news-release-details/netskope-announces-strong-second-quarter-fiscal-2027-financial'}],
                           'background_context': [],
                           'after_hours_change_pct': 16.0,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'Netskope',
                           'after_hours_reaction': {'change_pct': 16.0,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'},
                          {'ticker': 'CHPT',
                           'company_name': 'ChargePoint',
                           'company_description': '法人・集合住宅・家庭向けEV充電機器とネットワーク課金サービスを提供します。機器売上の回復だけでなく、継続収益、粗利率、キャッシュ消費を見る会社です。',
                           'source_url': 'https://www.sec.gov/Archives/edgar/data/1777393/000177739326000061/chpt8-kerfy2027q2exx991.htm',
                           'source_type': 'sec',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 2,
                           'search_queries': ['"CHPT" 2026-09-02 results',
                                              '"ChargePoint" investor relations 2026-09-02'],
                           'searched_sources': ['https://www.sec.gov/Archives/edgar/data/1777393/000177739326000061/chpt8-kerfy2027q2exx991.htm',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'],
                           'event_type': 'earnings',
                           'same_day_developments': [{'summary': 'Express '
                                                                 'Soloのearly-access出荷とEatonとの提携拡大を進めました。',
                                                      'evidence_tokens': ['Express Solo', 'Eaton'],
                                                      'source_url': 'https://www.sec.gov/Archives/edgar/data/1777393/000177739326000061/chpt8-kerfy2027q2exx991.htm',
                                                      'announced_at': '2026-09-02',
                                                      'temporal_status': 'same_day'}],
                           'why_moved': '売上が市場予想$105.43Mを上回り、過去最高の非GAAP粗利率38%とEBITDA損失縮小が、資金消費への懸念を和らげました。',
                           'investment_readthrough': 'EV販売台数だけでなく、法人充電網の更新とsubscription比率、Eaton経由の設備販売が収益性改善を左右します。',
                           'watch_items': ['Q3売上レンジの達成', 'subscription売上比率', '調整後EBITDAの黒字化時期'],
                           'qualitative_evidence': {'why_moved': ['$105.43M', '38%'],
                                                    'investment_readthrough': ['subscription',
                                                                               'Eaton']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://www.sec.gov/Archives/edgar/data/1777393/000177739326000061/chpt8-kerfy2027q2exx991.htm',
                                             'source_kind': 'sec'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'}],
                           'reported_results': [{'summary': 'Q2売上は$116.1Mで18%増、subscription売上は$43.7Mで10%増、調整後EBITDA損失は-$4.8Mでした。',
                                                 'evidence_tokens': ['$116.1M',
                                                                     '18%',
                                                                     '$43.7M',
                                                                     '10%',
                                                                     '-$4.8M'],
                                                 'source_url': 'https://www.sec.gov/Archives/edgar/data/1777393/000177739326000061/chpt8-kerfy2027q2exx991.htm'}],
                           'consensus_comparison': [{'summary': '調整後1株損失は-$1.35と市場予想-$1.60より小幅でした。',
                                                     'actual': '-$1.35',
                                                     'estimate': '-$1.60',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                    {'summary': '売上$116.1Mは市場予想$105.43Mを上回りました。',
                                                     'actual': '$116.1M',
                                                     'estimate': '$105.43M',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}],
                           'guidance': [{'summary': 'Q3売上は$105M–$115Mを見込みました。',
                                         'evidence_tokens': ['$105M–$115M'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/1777393/000177739326000061/chpt8-kerfy2027q2exx991.htm'}],
                           'guidance_comparison': [],
                           'key_kpis': [{'summary': '非GAAP粗利率は過去最高の38%、調整後EBITDA損失は前年の-$22.1Mから-$4.8Mへ縮小しました。',
                                         'evidence_tokens': ['38%', '-$22.1M', '-$4.8M'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/1777393/000177739326000061/chpt8-kerfy2027q2exx991.htm'}],
                           'background_context': [],
                           'after_hours_change_pct': 16.0,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'ChargePoint',
                           'after_hours_reaction': {'change_pct': 16.0,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'},
                          {'ticker': 'FIVE',
                           'company_name': 'Five Below',
                           'company_description': '若年層向けの低価格雑貨を店舗網で販売するディスカウント小売です。新店拡大だけでなく、既存店売上、商品回転、関税影響後の利益率が重要です。',
                           'source_url': 'https://www.sec.gov/Archives/edgar/data/1177609/000117760926000023/q22026fivebelowexhibit991.htm',
                           'source_type': 'sec',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 2,
                           'search_queries': ['"FIVE" 2026-09-02 results',
                                              '"Five Below" investor relations 2026-09-02'],
                           'searched_sources': ['https://www.sec.gov/Archives/edgar/data/1177609/000117760926000023/q22026fivebelowexhibit991.htm',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'],
                           'event_type': 'earnings',
                           'same_day_developments': [{'summary': '取締役会は新たに最大$600Mの自社株買いを承認しました。',
                                                      'evidence_tokens': ['$600M', '自社株買い'],
                                                      'source_url': 'https://www.sec.gov/Archives/edgar/data/1177609/000117760926000023/q22026fivebelowexhibit991.htm',
                                                      'announced_at': '2026-09-02',
                                                      'temporal_status': 'same_day'}],
                           'why_moved': '既存店14.1%増とEPS '
                                        'beatに加え、通期売上の上方修正と$600Mの自社株買いが下値を支えましたが、上昇幅は3%にとどまりました。',
                           'investment_readthrough': '低価格・トレンド商品の集客力は消費選別下でも強く、他のディスカウント小売には客数と在庫回転の改善を示します。',
                           'watch_items': ['下期既存店売上+10%–+12%の持続性', '関税還付後の粗利正常化', '新店生産性'],
                           'qualitative_evidence': {'why_moved': ['14.1%', '$600M'],
                                                    'investment_readthrough': ['低価格', '在庫回転']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://www.sec.gov/Archives/edgar/data/1177609/000117760926000023/q22026fivebelowexhibit991.htm',
                                             'source_kind': 'sec'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'}],
                           'reported_results': [{'summary': 'Q2売上は$1.26Bで22.9%増、既存店売上は14.1%増、調整後EPSは$1.68でした。',
                                                 'evidence_tokens': ['$1.26B',
                                                                     '22.9%',
                                                                     '14.1%',
                                                                     '$1.68'],
                                                 'source_url': 'https://www.sec.gov/Archives/edgar/data/1177609/000117760926000023/q22026fivebelowexhibit991.htm'}],
                           'consensus_comparison': [{'summary': '調整後EPSは$1.68と市場予想$1.39を上回りました。',
                                                     'actual': '$1.68',
                                                     'estimate': '$1.39',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}],
                           'guidance': [],
                           'guidance_comparison': [{'summary': 'FY26売上見通しを$5.40B–$5.48Bから$5.63B–$5.71Bへ引き上げました。',
                                                    'previous': '$5.40B–$5.48B',
                                                    'current': '$5.63B–$5.71B',
                                                    'direction': 'raised',
                                                    'source_url': 'https://www.sec.gov/Archives/edgar/data/1177609/000117760926000023/q22026fivebelowexhibit991.htm'}],
                           'key_kpis': [{'summary': '52店を純増して2,022店となり、既存店と新店の両方が成長へ寄与しました。',
                                         'evidence_tokens': ['52店', '2,022店'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/1177609/000117760926000023/q22026fivebelowexhibit991.htm'}],
                           'background_context': [],
                           'after_hours_change_pct': 3.0,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'Five Below',
                           'after_hours_reaction': {'change_pct': 3.0,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'},
                          {'ticker': 'TLYS',
                           'company_name': 'Tilly’s',
                           'company_description': '若者向け衣料・靴・アクセサリーを店舗とECで販売します。店舗縮小下での既存店成長、EC比率、粗利回復が黒字化の鍵です。',
                           'source_url': 'https://www.sec.gov/Archives/edgar/data/1524025/000162828026060088/q2fy2026earningsrelease.htm',
                           'source_type': 'sec',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 2,
                           'search_queries': ['"TLYS" 2026-09-02 results',
                                              '"Tilly’s" investor relations 2026-09-02'],
                           'searched_sources': ['https://www.sec.gov/Archives/edgar/data/1524025/000162828026060088/q2fy2026earningsrelease.htm',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'],
                           'event_type': 'earnings',
                           'same_day_developments': [],
                           'why_moved': '既存店の二桁成長と粗利率300bp改善がEPS '
                                        'beatへつながり、Q3も黒字を見込んだことで構造的なturnaround期待が強まりました。',
                           'investment_readthrough': '店舗数を減らしてもECと既存店の生産性が伸びており、若年層アパレルでは値引き抑制と在庫鮮度が利益回復を左右します。',
                           'watch_items': ['Q3既存店売上+10%–+14%', '商品粗利の改善継続', '通期黒字化'],
                           'qualitative_evidence': {'why_moved': ['300bp', 'Q3'],
                                                    'investment_readthrough': ['EC', '在庫鮮度']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://www.sec.gov/Archives/edgar/data/1524025/000162828026060088/q2fy2026earningsrelease.htm',
                                             'source_kind': 'sec'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'}],
                           'reported_results': [{'summary': 'Q2売上は$163.5Mで8.1%増、既存店売上は12.1%増、EPSは$0.27でした。',
                                                 'evidence_tokens': ['$163.5M',
                                                                     '8.1%',
                                                                     '12.1%',
                                                                     '$0.27'],
                                                 'source_url': 'https://www.sec.gov/Archives/edgar/data/1524025/000162828026060088/q2fy2026earningsrelease.htm'}],
                           'consensus_comparison': [{'summary': 'EPSは$0.27と市場予想$0.17を上回りました。',
                                                     'actual': '$0.27',
                                                     'estimate': '$0.17',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                    {'summary': 'Q3 '
                                                                'EPS見通し$0.07–$0.12は市場予想-$0.072を上回りました。',
                                                     'actual': '$0.07–$0.12',
                                                     'estimate': '-$0.072',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}],
                           'guidance': [{'summary': 'Q3売上を$150M–$155M、EPSを$0.07–$0.12の黒字レンジと見込みました。',
                                         'evidence_tokens': ['$150M–$155M', '$0.07–$0.12'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/1524025/000162828026060088/q2fy2026earningsrelease.htm'}],
                           'guidance_comparison': [],
                           'key_kpis': [{'summary': 'EC売上は20.9%増、粗利率は300bp改善し、13か月連続で既存店売上が前年を上回りました。',
                                         'evidence_tokens': ['20.9%', '300bp', '13か月'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/1524025/000162828026060088/q2fy2026earningsrelease.htm'}],
                           'background_context': [],
                           'after_hours_change_pct': 32.0,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'Tilly’s',
                           'after_hours_reaction': {'change_pct': 32.0,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'},
                          {'ticker': 'PVH',
                           'company_name': 'PVH',
                           'company_description': 'Calvin KleinとTommy '
                                                  'Hilfigerを世界展開するアパレル企業です。地域別のDTC・卸売動向と、値引き・関税を含むブランド利益率が焦点です。',
                           'source_url': 'https://www.sec.gov/Archives/edgar/data/78239/000007823926000055/ex99120262q8k.htm',
                           'source_type': 'sec',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 2,
                           'search_queries': ['"PVH" 2026-09-02 results',
                                              '"PVH" investor relations 2026-09-02'],
                           'searched_sources': ['https://www.sec.gov/Archives/edgar/data/78239/000007823926000055/ex99120262q8k.htm',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'],
                           'event_type': 'earnings',
                           'same_day_developments': [],
                           'why_moved': 'EPS beatでも売上は減少し、EMEAの6%減に対してFY26 '
                                        'EPSレンジを据え置いたため、利益の質と欧州需要への懸念が残りました。',
                           'investment_readthrough': '米州・APACのDTC改善だけでは欧州卸売の弱さを埋め切れず、グローバルアパレルでは地域ミックスと販促抑制が重要です。',
                           'watch_items': ['EMEA卸売の底入れ', 'DTC成長と粗利率', '関税還付を除く利益率'],
                           'qualitative_evidence': {'why_moved': ['EMEA', 'EPS'],
                                                    'investment_readthrough': ['APAC', 'DTC']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://www.sec.gov/Archives/edgar/data/78239/000007823926000055/ex99120262q8k.htm',
                                             'source_kind': 'sec'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'}],
                           'reported_results': [{'summary': 'Q2売上は$2.097Bで3%減、調整後営業利益率は11.1%、調整後EPSは$3.70でした。',
                                                 'evidence_tokens': ['$2.097B',
                                                                     '3%',
                                                                     '11.1%',
                                                                     '$3.70'],
                                                 'source_url': 'https://www.sec.gov/Archives/edgar/data/78239/000007823926000055/ex99120262q8k.htm'}],
                           'consensus_comparison': [{'summary': '調整後EPSは$3.70と市場予想$3.08を上回りました。',
                                                     'actual': '$3.70',
                                                     'estimate': '$3.08',
                                                     'outcome': 'beat',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                    {'summary': 'FY26 '
                                                                'EPS見通しの中央値$11.95は市場予想$12.08を下回りました。',
                                                     'actual': '$11.95',
                                                     'estimate': '$12.08',
                                                     'outcome': 'miss',
                                                     'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}],
                           'guidance': [{'summary': 'FY26調整後EPS見通しを$11.80–$12.10で据え置きました。',
                                         'evidence_tokens': ['$11.80–$12.10'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/78239/000007823926000055/ex99120262q8k.htm'}],
                           'guidance_comparison': [],
                           'key_kpis': [{'summary': 'EMEA売上は6%減、APACは3%増、e-commerceは4%増と地域差が続きました。',
                                         'evidence_tokens': ['EMEA', '6%', 'APAC', '3%', '4%'],
                                         'source_url': 'https://www.sec.gov/Archives/edgar/data/78239/000007823926000055/ex99120262q8k.htm'}],
                           'background_context': [],
                           'after_hours_change_pct': -3.0,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'PVH',
                           'after_hours_reaction': {'change_pct': -3.0,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'},
                          {'ticker': 'RARE',
                           'company_name': 'Ultragenyx',
                           'company_description': '希少疾患向け治療薬を開発・販売するバイオ医薬品企業です。今回は決算ではなく、Angelman症候群向け主力候補apazunersenの臨床価値を左右するPhase '
                                                  '3結果が焦点です。',
                           'source_url': 'https://ir.ultragenyx.com/news-releases/news-release-details/ultragenyx-announces-phase-3-aspire-results-angelman-syndrome',
                           'source_type': 'company_ir',
                           'search_status': 'verified_for_historical_migration',
                           'searched_at': '2026-09-03T12:04:39+09:00',
                           'search_attempt_count': 2,
                           'search_queries': ['"RARE" 2026-09-02 results',
                                              '"Ultragenyx" investor relations 2026-09-02'],
                           'searched_sources': ['https://ir.ultragenyx.com/news-releases/news-release-details/ultragenyx-announces-phase-3-aspire-results-angelman-syndrome',
                                                'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'],
                           'event_type': 'material_event',
                           'same_day_developments': [{'summary': '会社はapazunersenの扱いを再評価し、商業部門を支えながら大幅な費用削減を検討すると表明しました。',
                                                      'evidence_tokens': ['apazunersen', '費用削減'],
                                                      'source_url': 'https://ir.ultragenyx.com/news-releases/news-release-details/ultragenyx-announces-phase-3-aspire-results-angelman-syndrome',
                                                      'announced_at': '2026-09-02',
                                                      'temporal_status': 'same_day'}],
                           'why_moved': '主要・重要副次評価項目の双方が未達で、Phase '
                                        '1/2で見えた有効性を検証できず、apazunersenの成功確率とパイプライン価値が急低下しました。',
                           'investment_readthrough': 'Angelman症候群向けASO開発では小規模初期試験から比較試験へ進む際の再現性が課題となり、同領域の評価にも慎重さを促します。',
                           'watch_items': ['apazunersen継続可否', '費用削減の規模', 'UX111の承認判断と商業事業の資金創出'],
                           'qualitative_evidence': {'why_moved': ['双方が未達', 'apazunersen'],
                                                    'investment_readthrough': ['ASO', '再現性']},
                           'fact_sources': [{'label': '決算・正式発表',
                                             'url': 'https://ir.ultragenyx.com/news-releases/news-release-details/ultragenyx-announces-phase-3-aspire-results-angelman-syndrome',
                                             'source_kind': 'company_ir'}],
                           'market_context_sources': [{'label': '市場予想・時間外株価',
                                                       'url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                       'source_kind': 'financial_media'}],
                           'event_details': [{'summary': 'Phase 3 AspireはBayley-4認知raw '
                                                         'scoreの主要評価項目とMDRIの重要副次評価項目をともに達成できず、安全性はPhase '
                                                         '1/2と整合しました。',
                                              'evidence_tokens': ['Bayley-4', 'MDRI', '達成できず'],
                                              'source_url': 'https://ir.ultragenyx.com/news-releases/news-release-details/ultragenyx-announces-phase-3-aspire-results-angelman-syndrome'}],
                           'after_hours_change_pct': -40.0,
                           'as_of_utc': '2026-09-02T20:28:00Z',
                           'as_of_jst': '2026-09-03T05:28:00+09:00',
                           'session': 'post_market',
                           'display_company_name': 'Ultragenyx',
                           'after_hours_reaction': {'change_pct': -40.0,
                                                    'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                           'after_hours_price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                           'after_hours_price_provider': 'Investing.com'}],
 'after_hours_candidate_review': {'contract_version': 'ny_market_after_hours_v2',
                                  'discovery_method': 'broad_discovery_then_primary_verification',
                                  'market_session_date': '2026-09-02',
                                  'discovery_started_at': '2026-09-02T20:00:00Z',
                                  'discovery_completed_at': '2026-09-02T20:28:00Z',
                                  'discovery_runs': [{'scope': 'earnings_calendar',
                                                      'query': 'US earnings calendar 2026-09-02',
                                                      'source_url': 'https://www.nasdaq.com/market-activity/earnings',
                                                      'source_kind': 'secondary_discovery',
                                                      'status': 'completed'},
                                                     {'scope': 'after_hours_movers',
                                                      'query': 'US after-hours movers 2026-09-02',
                                                      'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                      'source_kind': 'secondary_discovery',
                                                      'status': 'completed'},
                                                     {'scope': 'regulatory_filings',
                                                      'query': 'SEC 8-K results 2026-09-02',
                                                      'source_url': 'https://www.sec.gov/edgar/search/',
                                                      'source_kind': 'official_registry',
                                                      'status': 'completed'},
                                                     {'scope': 'material_events',
                                                      'query': 'US clinical trial FDA '
                                                               'announcements 2026-09-02',
                                                      'source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                      'source_kind': 'secondary_discovery',
                                                      'status': 'completed'}],
                                  'coverage_status': 'normal',
                                  'discovered_candidate_count': 10,
                                  'candidates': [{'importance_rank': 1,
                                                  'ticker': 'AVGO',
                                                  'status': 'included',
                                                  'reason_code': 'verified_earnings',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['earnings_calendar',
                                                                    'after_hours_movers'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                 {'importance_rank': 2,
                                                  'ticker': 'SNOW',
                                                  'status': 'included',
                                                  'reason_code': 'verified_earnings',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['earnings_calendar',
                                                                    'after_hours_movers'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://www.sec.gov/Archives/edgar/data/1640147/000164014726000033/fy2027q2earnings.htm',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                 {'importance_rank': 3,
                                                  'ticker': 'HPE',
                                                  'status': 'included',
                                                  'reason_code': 'verified_earnings',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['earnings_calendar',
                                                                    'after_hours_movers'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://www.sec.gov/Archives/edgar/data/1645590/000164559026000078/ex-991x922026x8k.htm',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                 {'importance_rank': 4,
                                                  'ticker': 'NTAP',
                                                  'status': 'included',
                                                  'reason_code': 'verified_earnings',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['earnings_calendar',
                                                                    'after_hours_movers'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://investors.netapp.com/news/news-details/2026/NetApp-Reports-First-Quarter-of-Fiscal-Year-2027-Results/default.aspx',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                 {'importance_rank': 5,
                                                  'ticker': 'NTSK',
                                                  'status': 'included',
                                                  'reason_code': 'verified_earnings',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['earnings_calendar',
                                                                    'after_hours_movers'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://investors.netskope.com/news-releases/news-release-details/netskope-announces-strong-second-quarter-fiscal-2027-financial',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                 {'importance_rank': 6,
                                                  'ticker': 'CHPT',
                                                  'status': 'included',
                                                  'reason_code': 'verified_earnings',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['earnings_calendar',
                                                                    'after_hours_movers'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://www.sec.gov/Archives/edgar/data/1777393/000177739326000061/chpt8-kerfy2027q2exx991.htm',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                 {'importance_rank': 7,
                                                  'ticker': 'FIVE',
                                                  'status': 'included',
                                                  'reason_code': 'verified_earnings',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['earnings_calendar',
                                                                    'after_hours_movers'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://www.sec.gov/Archives/edgar/data/1177609/000117760926000023/q22026fivebelowexhibit991.htm',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                 {'importance_rank': 8,
                                                  'ticker': 'TLYS',
                                                  'status': 'included',
                                                  'reason_code': 'verified_earnings',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['earnings_calendar',
                                                                    'after_hours_movers'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://www.sec.gov/Archives/edgar/data/1524025/000162828026060088/q2fy2026earningsrelease.htm',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                 {'importance_rank': 9,
                                                  'ticker': 'PVH',
                                                  'status': 'included',
                                                  'reason_code': 'verified_earnings',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['earnings_calendar',
                                                                    'after_hours_movers'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://www.sec.gov/Archives/edgar/data/78239/000007823926000055/ex99120262q8k.htm',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'},
                                                 {'importance_rank': 10,
                                                  'ticker': 'RARE',
                                                  'status': 'included',
                                                  'reason_code': 'verified_material_event',
                                                  'reason': '正式発表と信頼できる時間外反応を検証できたため採用。',
                                                  'discovered_by': ['after_hours_movers',
                                                                    'material_events'],
                                                  'discovery_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740',
                                                  'discovery_source_kind': 'secondary_discovery',
                                                  'primary_source_url': 'https://ir.ultragenyx.com/news-releases/news-release-details/ultragenyx-announces-phase-3-aspire-results-angelman-syndrome',
                                                  'price_source_url': 'https://www.investing.com/news/stock-market-news/afterhours-movers-avgo-snow-hpe-ntap-ntsk-chpt-five-tlys-pvh-rare-432SI-4886740'}]}}
